### ISSUE TITLE
Sphinx Docstrings 

### ISSUE THREAD

**Issue by Deepthi-Nacharaju** [Deepthi-Nacharaju/bme590hrm#5]
Processing my sphinx doctrings in the terminal creates unpopulated html links :(

**Comment by mlp6** [comment]
Are you attempting to build this on the `master` branch?  Just asking to make sure that I can replicate this.

**Comment by Deepthi-Nacharaju** [comment]
the last time i tried it i was on a branch but it has since been merged to master. The branch im developing on now, make_test_work, hasn't changed anything regarding doc strings. is that what you're asking?

**Comment by mlp6** [comment]
Yep... will look into it later today when I'm done with meetings.

**Comment by mlp6** [comment]
Worked for me.  :)  Do you want to swing by this afternoon to work through this quick in person, or would you like for me to create a branch.  I followed the procedure here: https://github.com/mlp6/Medical-Software-Design/blob/master/Lectures/sphinx.md  But, something obviously is not clear, so I'd like to selfishly identify what that is to make it more clear.

**Comment by Deepthi-Nacharaju** [comment]
Still can't get it to work, because it won't overwrite existing sphinx files that i may have screwed up the first time. Or I could be expecting something different from the html links and it is right.... are you in your office at 2:45?

**Comment by mlp6** [comment]
Can you come by now (3:35?)

**Comment by mlp6** [comment]
We might not be able to cross paths in person, but don't worry about overwriting something; if it was important (something your wrote) it should be in your git history.  We can always re-create things that Sphinx generates.

**Comment by mlp6** [comment]
I will be on Slack this evening to answer questions more interactively if they pop up (will be biking home soon).

**Comment by Deepthi-Nacharaju** [comment]
i just left campus as well, i'll hop on slack later if that's easier. overwriting the sphinx files isn't given as an option, it just says quickstart won't overwrite them. When i try to run the rest of the commands with my existing sphinx files it says 
![image](https://user-images.githubusercontent.com/42826906/47458077-ba9a0880-d7a6-11e8-9730-6ec897175aa9.png)
and then all subsequent commands don't work either. I'm sure it's a small fix so if you'd rather do it in class tomorrow that's fine too!

**Comment by mlp6** [comment]
You can just blasts away the `docs/` directory an start over!

**Comment by Deepthi-Nacharaju** [comment]
Must be in docs folder to run make build
typo in napoleon in sphinx doc in instructions
